
OUTDIR=target/debug

$(OUTDIR)/step0_repl: FORCE
	cargo build --bin step0_repl

$(OUTDIR)/step1_read_print: FORCE
	cargo build --bin step1_read_print

$(OUTDIR)/step2_eval: FORCE
	cargo build --bin step2_eval

FORCE:
